// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifbugyacictyqtvbrcmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmYnVneWFjaWN0eXF0dmJyY21mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMDAwMzYsImV4cCI6MjA3MzY3NjAzNn0.a26MR3FobvHQQcIK4_cxH-q5VnyA4X6uiTIiDMUZjpo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});